### ISSUE TITLE
Songs with commas on their titles don't work.

### ISSUE THREAD

**Issue by juancabe** [1nikolas/tidal-lyrics#18]
I tried a few songs with commas on their names and they just didn't work. I don't know if this only happens to me, if it does, don't worry and close the issue.
Pd: thanks for this amazing tool!
![image](https://user-images.githubusercontent.com/65188763/130330655-dcbd8ecd-450d-48b0-9655-4e4e1bb9f754.png)
![image](https://user-images.githubusercontent.com/65188763/130330660-b1443000-edcf-4a4f-b82b-b1e6362521f7.png)

**Comment by juancabe** [comment]
If I made an error opening the issue, it's my first time opening one here, forgive me.

**Comment by 1nikolas** [comment]
Hello, can you give me an example song so I can fix it properly? Just right click and share the link with me. Thank you

**Comment by juancabe** [comment]
> Hello, can you give me an example song so I can fix it properly? Just right click and share the link with me. Thank you

Of course there are some examples:

https://tidal.com/track/184786802
https://tidal.com/track/7292296
https://tidal.com/album/5279052

**Comment by 1nikolas** [comment]
I think I fixed it.

![image](https://user-images.githubusercontent.com/30593419/130347905-2a1e6f12-b14b-473b-8db2-158364a21855.png)

I managed to get the bug only on the first song you sent. Can you install this build and see if it's actually fixed? Then I'll release an update. Thanks
https://www.dropbox.com/s/vg1y6uhee39lbs7/tidal-lyrics-testbuild%20Setup.exe?dl=0

**Comment by juancabe** [comment]
> If I made an error opening the issue, it's my first time opening one here, forgive me.

Solved :)

**Comment by 1nikolas** [comment]
> 
> 
> > If I made an error opening the issue, it's my first time opening one here, forgive me.
> 
> Solved :)

did the testbuild solve the problem? Should I push the fix?

**Comment by juancabe** [comment]
> > > If I made an error opening the issue, it's my first time opening one here, forgive me.
> > 
> > 
> > Solved :)
> 
> did the testbuild solve the problem? Should I push the fix?

As I told you, it's now working for me. I tried a few songs.

**Comment by 1nikolas** [comment]
okay thanks :)
