### ISSUE TITLE
Please make the window resizeable

### ISSUE THREAD

**Issue by mlidbom** [1nikolas/tidal-lyrics#2]
Thank you so much for this app. Not having lyrics is a big minus in a music app for me 👍 

It would really be nice to be able to resize the window though. When I'm singing along I really don't want to have to time and time again go grab the mouse and scroll the lyrics while trying to keep track of where the current line is. I have a 4k screen so the current window only uses something like a third of the height of my monitor :)

**Comment by 1nikolas** [comment]
@mlidbom it's already implumented (see [here](https://github.com/1nikolas/tidal-lyrics/commit/e86f9c67f59afce551eedbb923e375fc0cc23d60)) but I didn't want to make a new version just for that. Here is a prebuilt installer with that change (for Windows)
https://www.dropbox.com/s/m9fbvv0hnhbnyg3/tidal-lyrics-1.4.0%20Setup.exe?dl=0

**Comment by 1nikolas** [comment]
If you mean horizontal resize, it messes up the (poorly built) ui so can't do that

**Comment by mlidbom** [comment]
Vertical is definitely the important thing. Looking forward to a release where I can make it higher.
It might be a small code change but it's a huge change in the user experience :)

Edit: Oops sorry read too fast. Getting the installer now :)

**Comment by mlidbom** [comment]
Works like a charm. Thanks a bunch :)
