### ISSUE TITLE
Fails to find Simon & Garfunkel lyrics even though they are on Musixmatch

### ISSUE THREAD

**Issue by mlidbom** [1nikolas/tidal-lyrics#3]
Not a single Simon & Garfunkel song has worked for me so far. I looked up the last one to fail and it was on Musixmatch.

Just a guess, but might it be that tidal-lyrics fails to properly escape the '&' character and thus matching fails? Maybe some strategic spot needs a call to a UrlEscape method, or similar, to fix this for all special characters?

**Comment by 1nikolas** [comment]
I'll look on it rn

**Comment by mlidbom** [comment]
Thanks!
FYI. I'm using the updated build that you provided which allows for vertical resizing.

**Comment by 1nikolas** [comment]
It seems that Musixmatch doesn't understand `&` when the url is encoded (see here https://www.musixmatch.com/search/The%20Sound%20of%20Silence%20(Electric%20Version)*%20-%20Simon%20%26%20Garfunkel). Even if you type `Simon & Garfunkel` in the search and then refresh, it will break. So yeah I'll have to fix that..

**Comment by mlidbom** [comment]
So, you actually have to **not** url escape it for it to work. *smirk*
That is super veird :)

**Comment by 1nikolas** [comment]
Now it works
![image](https://user-images.githubusercontent.com/30593419/101947607-6ad26180-3bf9-11eb-9215-1c09adb6595a.png)

**Comment by mlidbom** [comment]
Fabulous! Will be eagerly awaiting a new build or release :)

**Comment by 1nikolas** [comment]
https://www.dropbox.com/s/m9fbvv0hnhbnyg3/tidal-lyrics-1.4.0%20Setup.exe?dl=0
Here is a windows build (took a while to upload, my internet is slow :( )

**Comment by mlidbom** [comment]
And it's working. Simply outstanding speed of providing a fix. 
Major kudos!
