### ISSUE TITLE
Scroll to and highlight current line.

### ISSUE THREAD

**Issue by mlidbom** [1nikolas/tidal-lyrics#4]
Hi, 

Most of the Lyrics on Musixmatch has timing information about each line. Musixmatch uses this in their own apps to automatically scroll to the current line and highlight it clearly. 

It would be awesome if this could be implemented in Tidal Lyrics. It really helps a lot not having to scan the lyrics to find the right spot, only to soon realize that it was not actually the right spot, just another similar part of the song. Not having to scroll time and time again is also very nice. No one really wants to go to the computer and start messing with the mouse when singing along :)

**Comment by 1nikolas** [comment]
I would do that if I could by unfortunately the way this app works is getting the lyrics from the Musixmatch webpage which doesn't have syncing information. The only way to get syncing information is to use [their api](https://developer.musixmatch.com/plans) which costs money (they don't even say how much, it just says contact us). Reverse engineering their app to find out how it gets syncing information is illegal and would get this repository DMCAed. So there is nothing I can do (unless there is a site with a free api which has synced lyrics but I don't think there is any)

**Comment by mlidbom** [comment]
Ah, that is unfortunate. But, as you say, nothing you can do about it then :(

**Comment by mlidbom** [comment]
Hmm. You might want to actually contact them. Some are reasonable with open source projects. It is not impossible that they will let you use it for free. Even if it is quite a long shot it might be worth the attempt if it does not take a lot of time to do.

**Comment by 1nikolas** [comment]
I don't think they'll do that. They sell that api to companies like Google (when you search {song name} lyrics) or Apple (for iTunes). But you never know. If they do that would be really nice

**Comment by 1nikolas** [comment]
Just contacted them. The thing is, the more I think about it, the more I think they'll say no.. Anyway we'll see

**Comment by mlidbom** [comment]
Well, there's hope until they refuse :)
Thanks a bunch for making the attempt!
