### ISSUE TITLE
Handle parenthesized title postfix comments 

### ISSUE THREAD

**Issue by mlidbom** [1nikolas/tidal-lyrics#6]
Many of the songs on Tidal have a parenthesized postfix to their title. Examples:

Title (Remastered)
Title (XXXX Remaster)
Title (Album Version)
Title (Single Version)

Tidal Lyrics usually fails to find lyrics for these songs even when they are on musixmatch without the postfix.

Suggestion: If the initial search fails and the song name has a postfix parenthesis, strip the postfix and the preceding whitespace and retry the search.

**Comment by 1nikolas** [comment]
Yeah I could do that. I mean it already retries twice..
https://github.com/1nikolas/tidal-lyrics/blob/f1e8ed04e29a9b721ed88e41afd0147dc2e59ed2/src/index.js#L276
https://github.com/1nikolas/tidal-lyrics/blob/f1e8ed04e29a9b721ed88e41afd0147dc2e59ed2/src/index.js#L292

**Comment by 1nikolas** [comment]
Can you send me an example so I can test if it works?

**Comment by mlidbom** [comment]
Sure, no problem :)
Tidal track link: https://tidal.com/browse/track/43725526
Musixmatch lyrics page: https://www.musixmatch.com/lyrics/Van-Halen/Drop-Dead-Legs

**Comment by 1nikolas** [comment]
Working now
![image](https://user-images.githubusercontent.com/30593419/101986931-b76d7980-3c99-11eb-91c6-3b2c55fdc3b5.png)

**Comment by mlidbom** [comment]
Beautiful :)
