### ISSUE TITLE
Windows PowerShell Error.

### ISSUE THREAD

**Issue by netowww** [1nikolas/tidal-lyrics#8]
![image](https://user-images.githubusercontent.com/23531577/104060414-9daa4e00-51d5-11eb-9672-9c752cd84af4.png)
I'm receiving this error when trying to use the App. I already installed the Last Version of PowerShell, but it didn't work.

Can you help me?

**Comment by 1nikolas** [comment]
Are you using Windows 10?

**Comment by netowww** [comment]
Yes! Windows 10.
[image: image.png]

**Comment by 1nikolas** [comment]
It seems that you sent an image but it didn't come through on Github.
Anyway, can you try opening cmd and typing powershell? Does that work?

**Comment by 1nikolas** [comment]
I think I know what's the problem. Does your user folder name contain a space? (you can find out by going on `C:\Users\`, your user folder is in there)

**Comment by netowww** [comment]
Yes, it does. My user name is João Batista. Is there something I can do to
keep my Username on Windows and use the Lyrics Application?

Yes, I can open powershell normally.

**Comment by 1nikolas** [comment]
> Is there something I can do to keep my Username on Windows and use the Lyrics Application?

Yes, I'll make a fix right now. I'll let you know when it's uploaded

**Comment by 1nikolas** [comment]
Okay it's uploaded. I updated the setup of version 1.5 so you will have to re-download the setup from the [releases](https://github.com/1nikolas/tidal-lyrics/releases). Let me know if your problem is fixed

**Comment by netowww** [comment]
Dear Nikolas,

Thank you very much, now it's working fine! You did a great job with this
app.

Best Regards,

João Batista Cordeiro Neto.
